### ISSUE TITLE
[d3] Cartesian integration bug on z axis

### ISSUE THREAD

**Issue by whitney-powers** [DedalusProject/dedalus#153]
Hello dedalus team. 
Here is a bug in d3 found when integrating a 2d field along the chebyshev axis (in this case z). This bug occurs in both parallel and serial. This bug does not happen in 3d when using a processor mesh.  Below you can find a minimal working example (run as python3 integration_bug.py) and the traceback I get from attempting to run this. 

Code:
```
import numpy as np
import dedalus.public as de
dtype = np.float64
dim = 2
dealias = 1.5
nx = nz = 8
Lx = Lz = 1

c = de.CartesianCoordinates('x','z')
d = de.Distributor(c, dtype=dtype)
xb = de.RealFourier(c.coords[0], size=nx, bounds=(0, Lx), dealias=dealias)
zb = de.ChebyshevT(c.coords[1], size=nz, bounds=(0, Lz), dealias=dealias)


b = (xb, zb)

integ_x = lambda A: de.Integrate(A,c.coords[0])
integ_z = lambda A: de.Integrate(A,c.coords[1])


T = d.Field(name='T', bases=b)
T['g'] = 1

T_int = integ_z(T).evaluate()
print(T_int['g'])
```
traceback:
```
Traceback (most recent call last):
  File "integration_test.py", line 24, in <module>
    T_int = integ_z(T).evaluate()
  File "/home/whitney/src/dedalus-d3/dedalus/core/future.py", line 195, in evaluate
    self.operate(out)
  File "/home/whitney/src/dedalus-d3/dedalus/core/operators.py", line 906, in operate
    apply_matrix(self.subspace_matrix(layout), arg.data, data_axis, out=out.data)
  File "/home/whitney/src/dedalus-d3/dedalus/tools/array.py", line 75, in apply_matrix
    return apply_dense(matrix, array, axis, **kw)
  File "/home/whitney/src/dedalus-d3/dedalus/tools/array.py", line 121, in apply_dense
    out[:] = temp # Copy
ValueError: could not broadcast input array from shape (1,8) into shape (8,1)

```

**Comment by evanhanders** [comment]
Hi everyone,

To add a wrinkle to this bug (and to help nail it down), this seems to only be a problem in 2D, and z-integration seems to work in 3D. See this attached code snippet (modified from above for 3D), which returns the expected result:

```
import numpy as np
import dedalus.public as de
dtype = np.float64
dim = 2 
dealias = 1.5 
nx = nz = 8 
Lx = Lz = Ly = 1 

c = de.CartesianCoordinates('x','y', 'z')
d = de.Distributor(c, dtype=dtype)
xb = de.RealFourier(c.coords[0], size=nx, bounds=(0, Lx), dealias=dealias)
yb = de.RealFourier(c.coords[1], size=nx, bounds=(0, Ly), dealias=dealias)
zb = de.ChebyshevT(c.coords[2], size=nz, bounds=(0, Lz), dealias=dealias)


b = (xb, yb, zb) 

integ_x = lambda A: de.Integrate(A,c.coords[0])
integ_y = lambda A: de.Integrate(A,c.coords[1])
integ_z = lambda A: de.Integrate(A,c.coords[2])


T = d.Field(name='T', bases=b)
T['g'] = zb.local_grid(1)

T_int = integ_z(T).evaluate()

print("z-integration working: {}".format(np.allclose(T_int['g'], 1/2)))
```
