### ISSUE TITLE
ValueError: mpi4py.MPI.File size changed, may indicate binary incompatibility.

### ISSUE THREAD

**Issue by zhaozhh** [DedalusProject/dedalus#186]
I had installed dedalus in the WSL 2 from source with Ubuntu 20.4. But when I run the first example I meet the following error message. Can someone help me? Thanks!

2022-03-26 17:14:17,578 dedalus 0/1 WARNING :: Threading has not been disabled. This may massively degrade Dedalus performance.
2022-03-26 17:14:17,578 dedalus 0/1 WARNING :: We strongly suggest setting the "OMP_NUM_THREADS" environment variable to "1".
Traceback (most recent call last):
  File "waves_on_a_string.py", line 21, in <module>
    import dedalus.public as d3
  File "/home/zhao/.local/lib/python3.8/site-packages/dedalus/public.py", line 4, in <module>
    from .core.coords import *
  File "/home/zhao/.local/lib/python3.8/site-packages/dedalus/core/__init__.py", line 2, in <module>
    from . import distributor
  File "/home/zhao/.local/lib/python3.8/site-packages/dedalus/core/distributor.py", line 23, in <module>
    from .transposes import FFTWTranspose as TransposePlanner
  File "dedalus/core/transposes.pyx", line 1, in init dedalus.core.transposes
ValueError: mpi4py.MPI.File size changed, may indicate binary incompatibility. Expected 40 from C header, got 32 from PyObject

**Comment by zhaozhh** [comment]
Installing it with anaconda without problem.
