### ISSUE TITLE
UnaryGridFunction sign generates TypeError

### ISSUE THREAD

**Issue by ntarshish** [DedalusProject/dedalus#80]
(First off, dedalus is an awesome tool and working with it has been great. Thanks for building it!)

The ``sign`` function generates ``TypeError: '<' not supported between instances of 'Field' and 'int' ``.  Could be related to the fact that ``sign`` is the only numpy function supported in the ``UnaryGridFunction``  class that returns ``int`` rather than ``float``. My code works without issue if I replace ``sign`` with another supported function, say, ``abs``.  

I am on dedalus version 2.1905. Here is the traceback:             
```
Traceback (most recent call last):
  File "plume.py", line 35, in <module>
    problem.add_equation("dt(b) - (1/(Re*Pr))*(dx(dx(b)) + dz(bz))             = -(u*dx(b) + w*bz) - sign(b)")
  File "/global/home/users/tarshish/miniconda3/envs/dedalus/lib/python3.8/site-packages/dedalus/core/problems.py", line 129, in add_equation
    self._build_object_forms(temp)
  File "/global/home/users/tarshish/miniconda3/envs/dedalus/lib/python3.8/site-packages/dedalus/core/problems.py", line 151, in _build_object_forms
    temp['RHS'] = future.FutureField.parse(temp['raw_RHS'], self.namespace, self.domain)
  File "/global/home/users/tarshish/miniconda3/envs/dedalus/lib/python3.8/site-packages/dedalus/core/future.py", line 235, in parse
    expression = eval(string, namespace)
  File "<string>", line 1, in <module>
TypeError: '<' not supported between instances of 'Field' and 'int'
```

Thank you in advance for your help.

**Comment by ntarshish** [comment]
My current workaround is to define a generalized function that explicitly performs the type conversion: 

```
def sign_float(*args):                                                                                                         
    x = args[0].data                                                                                                           
    return np.sign(x).astype('float')                                                                                          
                                                                                                                               
def sign_float_gf(*args):                                                                                                      
    return de.operators.GeneralFunction(domain, layout='g', func=sign_float, args=args)                                        
                                                                                                                               
de.operators.parseables['sign'] = sign_float_gf
```

**Comment by kburns** [comment]
Fixed in https://github.com/DedalusProject/dedalus/commit/2b04081dfec7575803b22cf735f44a832d3ad38d. Thanks!
