### ISSUE TITLE
Installation error in dedalus

### ISSUE THREAD

**Issue by gewitterblitz** [DedalusProject/dedalus#81]
Hi I am trying to install dedalus on my university supercomputer account. I am following the 'conda' installation procedure i.e. using bash install_conda.sh command.

Everything works fine till the last step i.e. installing dedalus with pip where I get the following error message:

```
ERROR: Command errored out with exit status 2:
   command: /home/sharm261/.conda/envs/cent7/5.3.1-py37/dedalus/bin/python3 /home/sharm261/.conda/envs/cent7/5.3.1-py37/dedalus/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-_gmufaj1/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'cython >= 0.22' 'mpi4py >= 2.0.0' numpy setuptools wheel
       cwd: None
  Complete output (30 lines):
  Collecting cython>=0.22
    Using cached Cython-0.29.20-cp38-cp38-manylinux1_x86_64.whl (1.9 MB)
  Processing /home/sharm261/.cache/pip/wheels/ff/61/0c/c516bd6b85f61f0acf333b0fbf5102fe39928a3563bf245a88/mpi4py-3.0.3-cp38-cp38-linux_x86_64.whl
  ERROR: Exception:
  Traceback (most recent call last):
    File "/home/sharm261/.conda/envs/cent7/5.3.1-py37/dedalus/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 188, in _main
      status = self.run(options, args)
    File "/home/sharm261/.conda/envs/cent7/5.3.1-py37/dedalus/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 185, in wrapper
      return func(self, options, args)
    File "/home/sharm261/.conda/envs/cent7/5.3.1-py37/dedalus/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 332, in run
      requirement_set = resolver.resolve(
    File "/home/sharm261/.conda/envs/cent7/5.3.1-py37/dedalus/lib/python3.8/site-packages/pip/_internal/resolution/legacy/resolver.py", line 179, in resolve
      discovered_reqs.extend(self._resolve_one(requirement_set, req))
    File "/home/sharm261/.conda/envs/cent7/5.3.1-py37/dedalus/lib/python3.8/site-packages/pip/_internal/resolution/legacy/resolver.py", line 362, in _resolve_one
      abstract_dist = self._get_abstract_dist_for(req_to_install)
    File "/home/sharm261/.conda/envs/cent7/5.3.1-py37/dedalus/lib/python3.8/site-packages/pip/_internal/resolution/legacy/resolver.py", line 314, in _get_abstract_dist_for
      abstract_dist = self.preparer.prepare_linked_requirement(req)
    File "/home/sharm261/.conda/envs/cent7/5.3.1-py37/dedalus/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 467, in prepare_linked_requirement
      local_file = unpack_url(
    File "/home/sharm261/.conda/envs/cent7/5.3.1-py37/dedalus/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 264, in unpack_url
      unpack_file(file.path, location, file.content_type)
    File "/home/sharm261/.conda/envs/cent7/5.3.1-py37/dedalus/lib/python3.8/site-packages/pip/_internal/utils/unpacking.py", line 249, in unpack_file
      unzip_file(
    File "/home/sharm261/.conda/envs/cent7/5.3.1-py37/dedalus/lib/python3.8/site-packages/pip/_internal/utils/unpacking.py", line 114, in unzip_file
      zip = zipfile.ZipFile(zipfp, allowZip64=True)
    File "/home/sharm261/.conda/envs/cent7/5.3.1-py37/dedalus/lib/python3.8/zipfile.py", line 1268, in __init__
      self._RealGetContents()
    File "/home/sharm261/.conda/envs/cent7/5.3.1-py37/dedalus/lib/python3.8/zipfile.py", line 1335, in _RealGetContents
      raise BadZipFile("File is not a zip file")
  zipfile.BadZipFile: File is not a zip file
  ----------------------------------------
ERROR: Command errored out with exit status 2: /home/sharm261/.conda/envs/cent7/5.3.1-py37/dedalus/bin/python3 /home/sharm261/.conda/envs/cent7/5.3.1-py37/dedalus/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-_gmufaj1/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'cython >= 0.22' 'mpi4py >= 2.0.0' numpy setuptools wheel Check the logs for full command output.
Installation complete in conda environment 'dedalus'
```

**Comment by jsoishi** [comment]
Thanks for reporting this. This is an upstream issue with conda. I'm afraid you'll have to pursue this with the Conda development team.
