### ISSUE TITLE
Q_time branch missing new_operand method for core.operators.TimeDerivative

### ISSUE THREAD

**Issue by bpbrown** [DedalusProject/dedalus#84]
I have a script that works on the current `d3` branch (commit 7bf49df2820f5b7346974716da1089866d124387) but fails on `Q_time` (commit d483dfc37a7bc58c41dcae687b6716bf3489e9c2) with error message about TimeDerivative:

```
Traceback (most recent call last):
  File "python/test_shell_conv.py", line 117, in <module>
    problem.add_equation(eq_eval("Ekman*ddt(u) - Ekman*lap(u) + grad(p) = Ekman*cross(curl(u), u) + Rayleigh*r_vec*T - 2*cross(ez, u)"), condition = "ntheta != 0")
  File "/home5/bpbrown/conda_install/src/dedalus-d3/dedalus/core/problems.py", line 155, in add_equation
    self._build_matrix_expressions(eqn)
  File "/home5/bpbrown/conda_install/src/dedalus-d3/dedalus/core/problems.py", line 503, in _build_matrix_expressions
    L = L.reinitialize(ncc=True, ncc_vars=vars)
  File "/home5/bpbrown/conda_install/src/dedalus-d3/dedalus/core/arithmetic.py", line 99, in reinitialize
    arg0 = self.args[0].reinitialize(**kw)
  File "/home5/bpbrown/conda_install/src/dedalus-d3/dedalus/core/arithmetic.py", line 99, in reinitialize
    arg0 = self.args[0].reinitialize(**kw)
  File "/home5/bpbrown/conda_install/src/dedalus-d3/dedalus/core/operators.py", line 607, in reinitialize
    operand = self.operand.reinitialize(**kw)
  File "/home5/bpbrown/conda_install/src/dedalus-d3/dedalus/core/arithmetic.py", line 806, in reinitialize
    arg1 = self.args[1].reinitialize(**kw)
  File "/home5/bpbrown/conda_install/src/dedalus-d3/dedalus/core/operators.py", line 608, in reinitialize
    return self.new_operand(operand)
  File "/home5/bpbrown/conda_install/src/dedalus-d3/dedalus/core/operators.py", line 612, in new_operand
    raise NotImplementedError("%s has not implemented the new_operand method." %type(self))
NotImplementedError: <class 'dedalus.core.operators.TimeDerivative'> has not implemented the new_operand method.
```

From further testing, it looks like the issue may be the multiplication by scalar in `Ekman*ddt(u)`, since an equivalent script with `ddt(u)` alone runs fine.

**Comment by kburns** [comment]
I think this should have been fixed with various changes to the arithmetic splitting methods, ending in 8de7ddf65608de713e4b1af03a2adec198ee646d.  Are scripts with terms like `Ekman*ddt(u)` working now on `d3`?
