### ISSUE TITLE
[d3] Power() operator is returning TypeError

### ISSUE THREAD

**Issue by bpbrown** [DedalusProject/dedalus#86]
In `d3` the `Power()` operator seems to have a call signature problem.  Or I'm using it wrong, but two attempts at implementation gave the same error.

In the first attempt I used the field overloaded operator (after editing fields to import from operators, see issue #85).

code:
```
Phi = trace(dot(e, e)) - 1/3*(trace_e**2)
```

error:
```
Traceback (most recent call last):
  File "j2011_hydro.py", line 191, in <module>
    Phi = trace(dot(e, e)) - 1/3*(trace_e**2)
  File "/home5/bpbrown/conda_install/src/dedalus-d3/dedalus/core/field.py", line 108, in __pow__
    return Power(self, other)
  File "/home5/bpbrown/conda_install/src/dedalus-d3/dedalus/tools/dispatch.py", line 26, in __call__
    args, kw = cls._preprocess_args(*args, **kw)
  File "/home5/bpbrown/conda_install/src/dedalus-d3/dedalus/core/operators.py", line 270, in _preprocess_args
    args = tuple(Operand.cast(arg, domain) for arg in args)
  File "/home5/bpbrown/conda_install/src/dedalus-d3/dedalus/core/operators.py", line 270, in <genexpr>
    args = tuple(Operand.cast(arg, domain) for arg in args)
TypeError: cast() missing 2 required positional arguments: 'tensorsig' and 'dtype'
```

I then tried to import the power operator myself and drive it directly:

```
power = lambda A, B: de.operators.Power(A, B)
Phi = trace(dot(e, e)) - 1/3*(power(trace_e,2))
```

which gave the same TypeError:

```
Traceback (most recent call last):
  File "j2011_hydro.py", line 191, in <module>
    Phi = trace(dot(e, e)) - 1/3*(power(trace_e,2))
  File "j2011_hydro.py", line 177, in <lambda>
    power = lambda A, B: de.operators.Power(A, B)
  File "/home5/bpbrown/conda_install/src/dedalus-d3/dedalus/tools/dispatch.py", line 26, in __call__
    args, kw = cls._preprocess_args(*args, **kw)
  File "/home5/bpbrown/conda_install/src/dedalus-d3/dedalus/core/operators.py", line 270, in _preprocess_args
    args = tuple(Operand.cast(arg, domain) for arg in args)
  File "/home5/bpbrown/conda_install/src/dedalus-d3/dedalus/core/operators.py", line 270, in <genexpr>
    args = tuple(Operand.cast(arg, domain) for arg in args)
TypeError: cast() missing 2 required positional arguments: 'tensorsig' and 'dtype'
```

**Comment by kburns** [comment]
Still an issue?

**Comment by kburns** [comment]
Closing as this seems to have been fixed at some point and powers are now working in d3.
